'''
Created on Jun 26, 2013

@author: phcostello
'''

#if __name__ == '__main__':

from mechanize import Browser
from bs4 import BeautifulSoup

mech = Browser()
url = 'http://finance.yahoo.com/q/cp?s=%5EFTSE'
page = mech.open(url)
path ='/home/phcostello/Documents/workspace/PatUtils/'
html = page.read()

#You need an html string here. Use google inspcet elements if generated by js
file = open(path + 'yahootable.txt')
html = file.read()
file.close()



soup = BeautifulSoup(html)
table = soup.find("table")
len(table)
print table
series = []
type(table)


for row in table.findAll('tr')[1:]:
    col = row.findAll('td')
    Symbol = col[0].string
    Name = col[1].string
    record = (Symbol, Name)
    series.append(','.join(record)+'\n')

series

fout = open(path + 'series.csv','w')

fout.writelines(series)


fout.close()